import { User } from '@prisma/client';
import { ERole } from '../../src/common/enum/base';

const users: User[] = [
  {
    id: 'U_1',
    firstName: 'Tuong',
    lastName: 'Anderson',
    fullName: 'Jack Anderson',
    role: ERole.MANAGER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'U_2',
    firstName: 'Claire',
    lastName: 'Redfield',
    fullName: 'Claire Redfield',
    role: ERole.LEADER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'U_3',
    firstName: 'Kevin',
    lastName: 'Kowalski',
    fullName: 'Kevin Kowalski',
    role: ERole.STAFF,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'U_4',
    firstName: 'Bill',
    lastName: 'Batson',
    fullName: 'Bill Batson',
    role: ERole.STAFF,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'U_5',
    firstName: 'Emily',
    lastName: 'Castle',
    fullName: 'Emily Castle',
    role: ERole.USER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'U_6',
    firstName: 'Anna',
    lastName: 'Pennyworth',
    fullName: 'Anna Pennyworth',
    role: ERole.USER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'U_7',
    firstName: 'John',
    lastName: 'Drake',
    fullName: 'John Drake',
    role: ERole.USER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'U_8',
    firstName: 'Ben',
    lastName: 'Anderson',
    fullName: 'Ben Anderson',
    role: ERole.USER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'U_9',
    firstName: 'Eva',
    lastName: 'Queen',
    fullName: 'Eva Queen',
    role: ERole.USER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'U_10',
    firstName: 'Evan',
    lastName: 'Todd',
    fullName: 'Evan Todd',
    role: ERole.USER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default users;
